import images from './images'

let works = [
    {
        backgroundImage: images.apose,
        title: 'Apose',
        description: 'Aplikasi kasir serbaguna untuk usaha kecil dan menengah.',
        googlePlay: true,
        googlePlayLink: '',
        website: false,
        websiteLink: '',
    },
    {
        backgroundImage: images.cbt,
        title: 'CBT',
        description: 'Aplikasi berbasis web untuk ulangan online.',
        googlePlay: false,
        googlePlayLink: '',
        website: true,
        websiteLink: '',
    },
    {
        backgroundImage: images.dumasPresisi,
        title: 'Dumas Presisi',
        description: 'Aplikasi Layanan Aduan Masyarakat untuk Mabes Polri.',
        googlePlay: true,
        googlePlayLink: '',
        website: true,
        websiteLink: '',
    },
    {
        backgroundImage: images.eauditBnn,
        title: 'E-Audit BNN',
        description: 'Aplikasi audit internal BNN RI.',
        googlePlay: false,
        googlePlayLink: '',
        website: false,
        websiteLink: '',
    },
    {
        backgroundImage: images.eSaberPungli,
        title: 'E-Saber Pungli',
        description: 'Aplikasi Satuan Tugas Sapu Bersih Pungutan Liar.',
        googlePlay: true,
        googlePlayLink: '',
        website: true,
        websiteLink: '',
    },
    {
        backgroundImage: images.ruangDosen,
        title: 'Ruang Dosen',
        description: 'Aplikasi Ruang Belajar untuk Semua.',
        googlePlay: true,
        googlePlayLink: '',
        website: true,
        websiteLink: '',
    },
    {
        backgroundImage: images.panenRaya,
        title: 'Panen Raya',
        description: 'Sebuah Forum Pertanian, Peternakan, dan Perikanan Indonesia.',
        googlePlay: false,
        googlePlayLink: '',
        website: false,
        websiteLink: '',
    },
    {
        backgroundImage: images.pemira,
        title: 'Pemira',
        description: 'Pemilihan Raya BEM Universitas Swadaya Gunung Jati.',
        googlePlay: false,
        googlePlayLink: '',
        website: false,
        websiteLink: '',
    },
    {
        backgroundImage: images.simprop,
        title: 'Simprop',
        description: 'Aplikasi Manajemen Properti.',
        googlePlay: false,
        googlePlayLink: '',
        website: false,
        websiteLink: '',
    },
    {
        backgroundImage: images.simrs,
        title: 'Simrs',
        description: 'Aplikasi Sistem Manajemen Rumas Sakit.',
        googlePlay: false,
        googlePlayLink: '',
        website: false,
        websiteLink: '',
    },
    {
        backgroundImage: images.spmhs,
        title: 'Spmhs',
        description: 'Aplikasi Surat Pengantar Mahasiswa Universitas Swadaya Gunung Jati.',
        googlePlay: false,
        googlePlayLink: '',
        website: false,
        websiteLink: '',
    },
]

export default works;